export enum Topic {
    ADDRESS = 'ADDRESS',
    BALANCE = 'BALANCE',
    WALLET_BLOCKS = 'WALLET_BLOCKS',
    WALLET_CREATE = 'WALLET_CREATE',
    TRANSFER = 'TRANSFER',
    WALLET = 'WALLET',
    REWARD = 'REWARD',
    LOCKSTEP = 'LOCKSTEP',
    QUERY = 'QUERY',
    SEED = 'SEED',
    PUBLISH = 'PUBLISH',
    SUBSCRIBE = 'SUBSCRIBE',
    SHARE = 'SECRET_SHARE',
    RECOVER = 'SECRET_RECOVER',
    JOIN = 'JOIN'
}