export enum Topic {
    ADDRESS = 'ADDRESS',
    BALANCE = 'BALANCE',
    BLOCKS = 'BLOCKS',
    CREATE = 'CREATE_WALLET',
    TRANSFER = 'TRANSFER',
    WALLET = 'WALLET',
    REWARD = 'REWARD',
    EJECT = 'EJECT',
    EVENT = 'EVENT',
    LOCKSTEP = 'LOCKSTEP',
    QUERY = 'QUERY',
    SEED = 'SEED',
    MESSAGE = 'MESSAGE',
    PUBLISH = 'PUBLISH',
    SUBSCRIBE = 'SUBSCRIBE',
    SHARE = 'SECRET_SHARE',
    RECOVER = 'SECRET_RECOVER'
}