export enum Topic {
    ADDRESS = 'ADDRESS',
    BALANCE = 'BALANCE',
    WALLET_BLOCKS = 'WALLET_BLOCKS',
    WALLET_CREATE = 'WALLET_CREATE',
    TRANSFER = 'TRANSFER',
    WALLET = 'WALLET',
    REWARD = 'REWARD',
    LOCKSTEP = 'LOCKSTEP',
    JOIN = 'JOIN',
    RPC = 'RPC'
}